component:
  name: chat-ui-operator
  namespace: ocm-system # fix: cannot be changed
  componentName: ui.privatellms.msp/chat-ui
  repositoryUrl: ghcr.io/apeirora/ocm
  secretRefName: ghcr-credentials
  semver: ">=0.8.0"
  interval: 1m

operator:
  targetNamespace: chat-ui
  publicHost: chat.localhost
  publicScheme: http
  imagePullSecretName: ghcr-credentials
  imagePullPolicy: IfNotPresent
  tlsSecretName: ""
  ingressExtraAnnotations: {}
