component:
  name: chat-ui
  namespace: ocm-system
  componentName: ui.privatellms.msp/chat-ui
  repositoryUrl: ghcr.io/apeirora/ocm
  secretRefName: ghcr-credentials
  semver: ">=0.8.0"
  interval: 1m

operator:
  targetNamespace: chat-ui
  publicHost: chat.localhost
  publicScheme: https
  tlsSecretName: ""
  imagePullSecretName: ghcr-credentials
  ingressExtraAnnotations: {}
