syncAgentOperator:
  enabled: true
  apiExportName: ui.privatellms.msp
  agentName: chat-ui-agent
  kcpKubeconfig: pm-kcp-kubeconfig
  extraFlags: []
  crds:
    enabled: false

publishedResources:
  enabled: true
  namespace: api-syncagent
  serviceAccountName: chat-ui-sync-agent
