image:
  repository: ghcr.io/apeirora/chat-ui-controller
  tag: 0.4.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []
manager:
  replicas: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
env:
  PUBLIC_HOST: chat.localhost
  PUBLIC_SCHEME: http
  INGRESS_EXTRA_ANNOTATIONS: '{}'
  TLS_SECRET_NAME: ''
rbac:
  create: true
serviceAccount:
  create: true
  name: ''
metrics:
  enabled: true
  service:
    type: ClusterIP
    port: 8080
